name: Publish simpleservers
# multiplatform docs: https://docs.docker.com/build/ci/github-actions/multi-platform/
on:
  push:
    tags:
    - 'v0.[0-9]+.[0-9]+'
  workflow_dispatch:
  
jobs:
  build-servers:
    runs-on: ubuntu-latest

    # howto: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    # publish specifi: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
    # permission keys: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    # by default only read permissions are enabled on the repo, need to allow pushing with the GITHUB_TOKEN
    # the permission defaults are reset when using the permission key, so need to reenable read
    permissions:
      contents: read
      packages: write


    #defaults:
    #  run:
    #    working-directory: ./build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up qemu for multi-platform building
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/actions/setup-go/
      # building in qemu
      #- uses: actions/setup-go@v5
      #  with:
      #    go-version: '1.22.2'

      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: static-file-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: rjwvandenberg/static-file-server:latest

      #- name: Build static-file-server:latest image
      #  run: docker build -t ghcr.io/rjwvandenberg/static-file-server:latest -f static-file-server/Dockerfile .

      #- name: Push static-file-server:latest image
      #  run: docker push ghcr.io/rjwvandenberg/static-file-server:latest
